# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: VaultReadKV@2
  inputs:
    strUrl: 'https://hvp.akeyless.io'
    ignoreCertificateChecks: true
    useProxy: 'none'
    strAuthType: 'clientToken'
    strToken: $VAULT_TOKEN
    strKVEnginePath: 'secret/data'
    kvVersion: 'v1'
    strSecretPath: '/azure/azuredevops'
    strPrefixType: 'custom'
    replaceCR: false


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

